version: '3'
services:
  ach:
    image: moov/ach:v1.2.1
    ports:
      - "8080:8080"
      - "9090:9090"
  accounts:
    image: moov/accounts:v0.4.1
    ports:
      - "8085:8085"
      - "9095:9095"
    environment:
      DEFAULT_ROUTING_NUMBER: '121042882'
  fed:
    image: moov/fed:v0.4.0
    ports:
      - "8086:8086"
      - "9096:9096"
  ofac:
    image: moov/ofac:v0.11.1
    ports:
      - "8084:8084"
      - "9094:9094"
  auth:
    image: moov/auth:v0.8.0
    ports:
      - "8081:8081"
      - "9091:9091"
  paygate:
    image: moov/paygate:latest
    ports:
      - "8082:8082"
      - "9092:9092"
    command: ["-http.addr", ":8082"]
    environment:
      ACCOUNTS_ENDPOINT: 'http://accounts:8085'
      ACH_ENDPOINT: 'http://ach:8080'
      FED_ENDPOINT: 'http://fed:8086'
      OFAC_ENDPOINT: 'http://ofac:8084'
      ACH_FILE_MAX_LINES: 20 # upload files when they're a lot smaller than the 10k default
      ACH_FILE_TRANSFER_INTERVAL: 30s # Merge and Upload files this often
    depends_on:
      - ach
      - accounts
      - fed
      - ofac
      - auth
