version: '3'

networks:
  local:

services:
  ach:
    image: moov/ach:v1.2.1
    ports:
      - "8080:8080"
    networks:
      - local
  accounts:
    image: moov/accounts:v0.4.1
    ports:
      - "8085:8085"
    networks:
      - local
    environment:
      DEFAULT_ROUTING_NUMBER: '121042882'
  fed:
    image: moov/fed:v0.4.0
    ports:
      - "8086:8086"
    networks:
      - local
  ofac:
    image: moov/ofac:v0.11.1
    ports:
      - "8084:8084"
    networks:
      - local
  auth:
    image: moov/auth:v0.8.0
    ports:
      - "8081:8081"
    networks:
      - local
  paygate:
    image: moov/paygate:latest
    ports:
      - "8082:8082"
      - "9092:9092"
    networks:
      - local
    environment:
      ACCOUNTS_ENDPOINT: 'http://accounts:8085'
      ACH_ENDPOINT: 'http://ach:8080'
      FED_ENDPOINT: 'http://fed:8086'
      OFAC_ENDPOINT: 'http://ofac:8084'
      ACH_FILE_MAX_LINES: 20 # upload files when they're a lot smaller than the 10k default
      ACH_FILE_TRANSFER_INTERVAL: 30s # Merge and Upload files this often
    entrypoint: '/bin/bash -c'
    command:
      - 'apt-get update -q && apt-get install -y curl && curl -v http://fed:8086/ping && /bin/paygate'
    depends_on:
      - ach
      - accounts
      - fed
      - ofac
      - auth
